# -*- coding: utf-8 -*-
"""game

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17CLO_cNa2R1a4-cNLaADM1SX00SZjkLg
"""

import random
print(random.randint(1,10))

from random import randint
choice=['rock','paper','scissor']
limit=3
ps=0
cs=0
while True:
  player=input("choose from choice").lower()
  comp=choice[randint(0,2)]
  print("computer chooses:",comp)
  if player==comp:
    print("Draw match")
  elif player=="paper" and comp=="rock":
    print("player 1 wins")
    ps+=1
  elif player=="rock" and comp=="scissor":
    print("player 1 wins")
    ps+=1
  elif player=="scissor" and comp=="paper":
    print("player 1 wins")
    ps+=1
  else:
    print("computer win")
    cs+=1
  if ps == limit or cs == limit:
    break
if ps>cs:
  print("player 1 wins")
else:
  print("computer wins")

